/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChitChat;

/**
 *
 * @author NKC
 */
public class Emoj extends javax.swing.JPanel {

    /**
     * Creates new form Emoj
     */
    public Emoj() {
        initComponents(); 
    }
public void setMsg(String msg,String us)
 {
     //System.out.println("ha");
     usn.setText(us);
     emoji.setOpaque(false);
     if((!msg.equals(""))&& msg.substring(0,6).equals("a$$$$$"))
     {
         try{
     emoji.setIcon(new javax.swing.ImageIcon(
               getClass().getResource("/ChitChat/bigemoj/"+msg+".png")));
         }
         catch(Exception ex)
         {
             emoji.setIcon(new javax.swing.ImageIcon(
               getClass().getResource("/ChitChat/bigemoj/"+msg+".gif")));
         }
     }
     else
     {
         System.out.println(msg +" nahi aya 1");
     }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emoji = new javax.swing.JLabel();
        usn = new javax.swing.JLabel();

        setOpaque(false);

        usn.setBackground(new java.awt.Color(0, 153, 51));
        usn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        usn.setForeground(new java.awt.Color(0, 102, 0));
        usn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ChitChat/r1.png"))); // NOI18N
        usn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(emoji, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usn)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emoji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(usn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emoji;
    private javax.swing.JLabel usn;
    // End of variables declaration//GEN-END:variables
}
